version: '3'
services:
  app:
    build: .
    command: gunicorn --config gunicorn.conf main:app
    volumes:
      - ./partypi/:/partypi/partypi/
      - static_volume:/static_volume
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 8000:8000
    env_file: config.env
    image: "gcr.io/${PROJECT_ID}/partypi:v1"

  tfserving:
    image: "justinshenk/emotion_serving"
    ports:
      - "8501:8501"
      - "8500:8500"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static_volume
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  static_volume:
