version: '3'
services:
  app:
    build: .
    command: gunicorn --chdir /partypi/partypi/ main:app --bind 0.0.0.0:5000
    volumes:
      - ./partypi/:/partypi/partypi/
      - static_volume:/static_volume
    ports:
      - 5000:5000
    env_file: config.env
    image: "gcr.io/${PROJECT_ID}/partypi:v1"

  tfserving:
    image: "justinshenk/emotion_serving"
    ports:
      - "8501:8501"
      - "8500:8500"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
            #- static_volume:/static_volume
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  static_volume:
